### ISSUE TITLE
Ads not showing up in release mode

### ISSUE THREAD

**Issue by sophatvathana-slash** [StartApp-SDK/flutter-plugin#8]
Hi, 
I have an app that is supposed to show some ads. In debug mode, everything runs fine, ads are showing up as they should be.
Even though I try your example also not working in release mode, in debugging everything runs fine.
Thanks

```
 I/flutter (16414): Error loading Banner ad: PlatformException(failed_to_receive_ad, Ad wasn't loaded: serving ads disabled, null, null)
I/flutter (16414): Error loading Banner ad: PlatformException(failed_to_receive_ad, Ad wasn't loaded: serving ads disabled, null, null)
I/flutter (16414): Error loading Banner ad: PlatformException(failed_to_receive_ad, Ad wasn't loaded: serving ads disabled, null, null)
I/flutter (16414): Error loading Banner ad: PlatformException(failed_to_receive_ad, Ad wasn't loaded: serving ads disabled, null, null)
I/flutter (16414): Error loading Mrec ad: PlatformException(failed_to_receive_ad, Ad wasn't loaded: serving ads disabled, null, null)
I/flutter (16414): Error loading Native ad: PlatformException(loading_error, Ad wasn't loaded: serving ads disabled, null, null)
I/flutter (16414): Error loading Mrec ad: PlatformException(failed_to_receive_ad, Ad wasn't loaded: serving ads disabled, null, null)
I/flutter (16414): Error loading Banner ad: PlatformException(failed_to_receive_ad, Ad wasn't loaded: serving ads disabled, null, null)
I/flutter (16414): Error loading Banner ad: PlatformException(failed_to_receive_ad, Ad wasn't loaded: serving ads disabled, null, null)
I/flutter (16414): Error loading Rewarded Video ad: PlatformException(failed_to_receive_ad, serving ads disabled, null, null)
I/flutter (16414): Error loading Interstitial ad: PlatformException(failed_to_receive_ad, serving ads disabled, null, null)
I/flutter (16414): Error loading Interstitial ad: PlatformException(failed_to_receive_ad, serving ads disabled, null, null)
```

**Comment by StartApp-SDK** [comment]
Hi, the error message means that your account is blocked or you did a lot of request per one day ( > 1000)

**Comment by sophatvathana** [comment]
> Hi, the error message means that your account is blocked or you did a lot of request per one day ( > 1000)

Thank you for your support

**Comment by Syed-Waleed-Shah** [comment]
> Hi, the error message means that your account is blocked or you did a lot of request per one day ( > 1000)

It means we cannot even request more than 1000 times??? If this is the case then what about those apps who have more than 100k daily active users?

**Comment by StartApp-SDK** [comment]
Hi Syed-Waleed-Shah, 1000 times per day means for one user, so all the apps with 100k daily active users will work perfect because every user has his own unique advertiser id. So seems that blocked only this advertiser id from which you requested these 1000 requests. So try to go settings google ads and reset your advertiser id.

**Comment by Syed-Waleed-Shah** [comment]
> Hi Syed-Waleed-Shah, 1000 times per day means for one user, so all the apps with 100k daily active users will work perfect because every user has his own unique advertiser id. So seems that blocked only this advertiser id from which you requested these 1000 requests. So try to go settings google ads and reset your advertiser id.

Hi @StartApp-SDK , I appreciate your quick response. Can you please tell me why you are showing privacy consent dialog at your own in production when user opens app for the first time after installing? I have app with 500k+ install on playstore. I recently integrated startapp because too many fellows suggested me this. No doubt it is good monetization network but recently I am getting lots of reviews from our users and they tell that app is not opening. When we ask for screenshots of issue, they send us screenshots where startapp privacy dialog is opened. Please try to resolve following 2 issues ASAP (otherwise I will have to remove startapp):
1) Make privacy consent dialog optional.
2) Add option in flutter code to enable/disable splash ads.

**Comment by StartApp-SDK** [comment]
will be great if you can send us such screenshots or video. Because nobody complained before, so to better understand how to fix the issue we need to reproduce it. we are going to add such method for disabling consent in 1-2 days (it exists in native android/ios sdk so we need only make a bridge). And splash as well.

**Comment by Syed-Waleed-Shah** [comment]
> will be great if you can send us such screenshots or video. Because nobody complained before, so to better understand how to fix the issue we need to reproduce it. we are going to add such method for disabling consent in 1-2 days (it exists in native android/ios sdk so we need only make a bridge). And splash as well.

Yeah for sure. Its 01:15AM here! I was about to shut my system down and got your reply. Will be sharing screenshots with you.
