### ISSUE TITLE
Remove privacy screen

### ISSUE THREAD

**Issue by behzad-tg** [StartApp-SDK/flutter-plugin#9]
in first run for user, startapp privacy screen show up.
how can remove that?

i have a privacy screen for my app in first run, and showe
if startapp privacy is importan to show, how can add to my parivacy screen???

**Comment by Syed-Waleed-Shah** [comment]
Yes i am facing the same issue. There should be option to remove privacy screen on the first launch other wise I am removing this monetization because some of my users (most probably users who have android v5 or android v13) are not able to even open the app due to this permission dialog.

**Comment by StartApp-SDK** [comment]
Hi, all the users even on android 5 and 13 should be able to press the buttons on this privacy dialog. But ok, we will add a method in our api and you will be able to disable the dialog by calling it. But this can affect your revenue because good advertisers prefer to have such consent from the user.

**Comment by StartApp-SDK** [comment]
Put this lines into your AndroidManifest.xml to disable it:

```xml
<meta-data
    android:name="com.startapp.sdk.CONSENT_ENABLED"
    android:value="false" />
```
